from pathlib import Path, PurePath
from typing import Dict, Iterable

import napari
import numpy as np
from brainglobe_atlasapi import BrainGlobeAtlas


def open_parameter_file(file_path: Path) -> Dict:
    """
    Opens the parameter file and returns the parameter dictionary.

    This function reads a parameter file and extracts the parameters into
    a dictionary. The parameter file is expected to have lines in the format
    "(key value1 value2 ...)". Any line not starting with "(" is ignored.
    The values are stripped of any trailing ")" and leading or trailing quotes.

    Parameters
    ------------
    file_path : Path
        The path to the parameter file.

    Returns
    --------
    Dict
        A dictionary containing the parameters from the file.
    """
    with open(file_path, "r") as f:
        param_dict = {}
        for line in f.readlines():
            if line[0] == "(":
                split_line = line[1:-1].split()
                cleaned_params = []
                for i, entry in enumerate(split_line[1:]):
                    if entry == ")" or entry[0] == "/":
                        break

                    cleaned_params.append(entry.strip('" )'))

                param_dict[split_line[0]] = cleaned_params

    return param_dict


def _is_numeric_token(token: str) -> bool:
    if token == "":
        return False
    try:
        float(token)
    except ValueError:
        return False
    return True


def _format_parameter_values(values: Iterable[str]) -> str:
    formatted_values = []
    for value in values:
        cleaned_value = value.strip().strip('"')
        if _is_numeric_token(cleaned_value):
            formatted_values.append(cleaned_value)
        else:
            formatted_values.append(f'"{cleaned_value}"')
    return " ".join(formatted_values)


def write_parameter_file(file_path: Path, param_dict: Dict) -> None:
    """
    Writes a parameter dictionary to a file in elastix format.

    Each parameter is written in the format:
    (Key value1 value2 ...)
    """
    with open(file_path, "w") as f:
        f.write("// Generated by brainglobe-registration\n")
        for key, values in param_dict.items():
            if values:
                formatted_values = _format_parameter_values(values)
                f.write(f"({key} {formatted_values})\n")
            else:
                f.write(f"({key})\n")


def serialize_registration_widget(obj):
    if isinstance(obj, napari.layers.Layer):
        return obj.name
    elif isinstance(obj, napari.Viewer):
        return str(obj)
    elif isinstance(obj, PurePath):
        return str(obj)
    elif isinstance(obj, BrainGlobeAtlas):
        return obj.atlas_name
    elif isinstance(obj, np.ndarray):
        return f"<{type(obj)}>, {obj.shape}, {obj.dtype}"
    else:
        return obj.__dict__()
